swagger: '2.0'
info:
  description: Kinetic Smart Swagger Implementatin
  version: "1.0.0"
  title: Kinetic Smart API

  contact:
    email: dev@citypay.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

securityDefinitions:
  BasicAuth:
    type: basic

paths:

  /ping.json:
    get:
      tags:
      - device
      produces:
      - application/json
      summary: Simple function to detect the presence of the device on the network. Typically, only used for system setup validation and testing.
      responses:
        200:
          description: Response of a ping request
          schema:
            $ref: '#/definitions/PingResponse'

  /battery.json:
    get:
      tags:
      - device
      security:
        - BasicAuth: []
      produces:
      - application/json
      summary:  Request the status of the battery on the device.
      responses:
        200:
          description: Information on the given device
          schema:
            $ref: '#/definitions/BatteryResponse'
        403:
          description: Unauthorized access

  /sale.json:
    post:
      tags:
      - payment
      security:
        - BasicAuth: []
      consumes:
      - application/json
      produces:
      - application/json
      summary: Initiate a sale transaction on the device.
      parameters:
      - name: body
        required: true
        in: body
        schema:
          $ref: '#/definitions/SaleRequest'
      responses:
        200:
          description: When a transaction has been initiated, use GET transaction.json to follow the progress and retrieve the result of a transaction when it is completed.
          schema:
            $ref: '#/definitions/SaleResponse'
        403:
          description: Unauthorized to access the device

  /refund.json:
    post:
      tags:
      - payment
      security:
        - BasicAuth: []
      consumes:
      - application/json
      produces:
      - application/json
      summary: Initiate a refund transaction on the device.
      parameters:
      - name: body
        required: true
        in: body
        schema:
          $ref: '#/definitions/SaleRequest'
      responses:
        200:
          description: When a transaction has been initiated, use GET transaction.json to follow the progress and retrieve the result of a transaction when it is completed.
          schema:
            $ref: '#/definitions/SaleResponse'
        403:
          description: Unauthorized to access the device

  /reversal.json:
    post:
      tags:
      - payment
      security:
        - BasicAuth: []
      consumes:
      - application/json
      produces:
      - application/json
      summary: Initiate a reversal on the device.
      parameters:
      - name: body
        required: true
        in: body
        schema:
          $ref: '#/definitions/ReversalRequest'
      responses:
        200:
          description: When a transaction has been initiated, use GET transaction.json to follow the progress and retrieve the result of a transaction when it is completed.
          schema:
            $ref: '#/definitions/SaleResponse'
        403:
          description: Unauthorized to access the device

  /close.json:
    post:
      tags:
      - payment
      security:
        - BasicAuth: []
      produces:
      - application/json
      summary: When this instruction is sent, the reconciliation process will be started and the transactions for the day closed. Important, no confirmation is prompted on the device.
      responses:
        200:
          description: When a transaction has been initiated, use GET transaction.json to follow the progress and retrieve the result of a transaction when it is completed.
          schema:
            $ref: '#/definitions/CloseResponse'
        403:
          description: Unauthorized to access the device

  /print.json:
    post:
      tags:
      - payment
      security:
        - BasicAuth: []
      consumes:
      - application/json
      produces:
      - application/json
      summary: Reprint a merchant or customer receipt for a transaction that exists on the device (i.e. has not been cleared by End of Day process).
      parameters:
      - name: body
        required: true
        in: body
        schema:
          $ref: '#/definitions/PrintRequest'
      responses:
        200:
          description: When a transaction has been initiated, use GET transaction.json to follow the progress and retrieve the result of a transaction when it is completed.
          schema:
            $ref: '#/definitions/SuccessResponse'
        403:
          description: Unauthorized to access the device

  /transaction.json:
    post:
      tags:
      - payment
      summary: Request the status of a transaction in progress or a complete transaction using the uuid as the reference.

        Depending on the state of the transaction, the response will indicate if it is not found, in progress (and the current stage in the transaction workflow) or complete (with all the disarmed transaction data).
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/TransactionProgress'
      responses:
        200:
          description: Information regarding the progress of the transaction
          schema:
            $ref: '#/definitions/TransactionResult'
        403:
          description: Unauthorized to access the device
          schema:
            $ref: '#/definitions/Result'


definitions:

  PingResponse:
    type: object
    properties:
      ping:
        type: boolean

  BatteryResponse:
    type: object
    properties:
      success:
        type: boolean
      charging:
        type: boolean
      percentage:
        type: integer

  SaleRequest:
    type: object
    required:
    - amount
    properties:
      amount:
        type: integer
        description: The amount to process in the lowest denomination and in the base currency of the device. 100 for instance would process the transaction for £1.00
        example: 100
      uuid:
        type: string
        description: Can include a unique identifier (uuid) for this transaction, but if none present a new UUID will be assigned and returned. Note, does not have to be a uuid
        example: 0600ee0b-69df-4b77-cbb5-8a20962a75ab


  SaleResponse:
    type: object
    required:
    - success
    properties:
      success:
        type: boolean
        description: Defines whether the sale was successfully created
      uuid:
        type: string
        example: 0600ee0b-69df-4b77-cbb5-8a20962a75ab
      description:
        type: string
        description: Description should the sale request not be accepted

  ReversalRequest:
    type: object
    required:
    - uuid
    properties:
      uuid:
        type: string
        description: Must include the unique identifier (uuid) for the transaction transaction to be reversed.
        example: 0600ee0b-69df-4b77-cbb5-8a20962a75ab

  PrintRequest:
    type: object
    required:
    - uuid
    properties:
      uuid:
        type: string
        description: Must include a UUID for a transaction that has been carried out on the device
        example: 0600ee0b-69df-4b77-cbb5-8a20962a75ab
      type:
        type: string
        description: The instruction prints the cardholder copy of the receipt by default. If you want to reprint the merchant copy, append “type”:”merchant” to the body of the request.

  SuccessResponse:
    type: object
    required:
    - success
    properties:
      success:
        type: boolean
        example: false
      description:
        type: string
        description: Message describing any error
        example: Transaction in progress
      status:
        type: string
        description: status of the device
        example: Prompting for payment

  CloseResponse:
    type: object
    required:
    - success
    properties:
      success:
        type: boolean
        description: Indicates that the reconciliation process is now underway on the device.
      uuid:
        type: string
        example: 0600ee0b-69df-4b77-cbb5-8a20962a75ab



  TransactionProgress:
    type: object
    required:
      - uuid
    properties:
      uuid:
        type: string
        description: The uuid to check the progress on
        example: 0600ee0b-69df-4b77-cbb5-8a20962a75ab


  # here



  TransactionResult:
    type: object
    properties:
      additional_data:
        type: string
        description: additional data provided within the acquirer response
        example: "000800"
      auxiliary_data:
        type: string
        description: Value provided by online processing
        example: "CEAB962F"
      card_type:
        type: string
        description: The type of card used such as EMV
        example: "EMV"
      completed_at:
        type: string
        description: The date and time that the transaction was completed in ISO-8166 format
        example: '2017-11-01T08:54:23'
      created_at:
        type: string
        description: The date and time that the transaction was created in ISO-8166 format
        example: '2017-11-01T08:54:09'
      currency_symbol:
        type: string
        description: The currency symbol used
        example: "£"
      customer_receipt:
        type: string
        description: The customer receipt to print
      declined_by_card:
        type: boolean
        description: Boolean value should the transaction be declined by the card
        example: false
      emv_app_cryptogram:
        type: string
        description: Cryptogram used by the card in processing
        example: "CDC35CA0090BC8"
      emv_app_expiration_date:
        type: string
        description: Expiry date of the card
        example: "1121"
      emv_app_txn_counter:
        type: integer
        description: A transaction counter, incremented by the device resulting in a transaction number
        example: 5
      emv_authorized_amount:
        type: string
        description: The amount authorised
        example: 100
      emv_cardholder_verification_results:
        type: string
        description: Verification results within the processing scope
        example: "3F0000"
      emv_country_code:
        type: string
        description: A country code returned by the device
        example: "826"
      emv_cryptogram_info_data:
        type: string
        description: Cryptogram info returned by the card
        example: "80"
      emv_icc_appid:
        type: string
        description: The application id (AID) identifying the card used
        example: "A0000000031010"
      emv_interchange_profile:
        type: string
        description: The interchange profile used
        example: "+00"
      emv_issuer_app_data:
        type: string
        description: Application data provided by the issuer
        example: "06011103A00000"
      emv_pan_seq_num:
        type: string
        description: Sequence number provided by the card
        example: "01"
      emv_terminal_capabilities:
        type: string
        description: Terminal capabilities of the device
        example: "E0B0C8"
      emv_terminal_type:
        type: string
        description: The terminal type of the device
        example: "22"
      emv_terminal_verification_results:
        type: string
        description: TVR provided by the verification process of the transaction
        example: "0000000000"
      emv_track2_equivalent:
        type: string
        description: A masked version of the card number
        example: "4***********0010"
      emv_txn_currency_code:
        type: string
        description: ISO currency code of the transaction
        example: "840"
      emv_txn_date:
        type: string
        description: ISO date of the transaction
        example: "2017-11-01"
      emv_txn_status_info:
        type: string
        description: Status info of the transaction
        example: "0000"
      emv_txn_type:
        type: string
        description: Transacrtion type information returned
        example: "00"
      emv_txn_unpredictable_number:
        type: string
        description: The UN or unpredicatble number in the transaction process
        example: "FF10616"
      is_commercial_card:
        type: string
        description: Determines if the card was a commercial card
        example: false
      is_contactless:
        type: string
        description: Determines if the card was contactless
        example: true
      is_fallback:
        type: string
        description: Determines if fallback was used
        example: false
      is_offline:
        type: string
        description: Determines if the transaction was authorised offline
        example: false
      is_voided:
        type: string
        description: Determines if the transaction was voided
        example: false
      merchant_receipt:
        type: string
        description: The merchant receipt
      response_code:
        type: string
        description: A response code provided by the acquirer
        example: "00"
      response_text:
        type: string
        description: The response text returned by the acquirer
        example: "AUTH CODE 604405"
      result:
        type: string
        description: A text result of the transaction
        example: "approved"
      scheme:
        type: string
        description: A description of the card scheme for the card
        example: "visa-qvsdc"
      signature_required:
        type: string
        description: Determines whether a signature was required for legacy systems
        example: false
      terminal_id:
        type: string
        description: The terminal id used from the device
        example: "33420006"
      total_amount:
        type: integer
        description: The total amount processed
        example: 100
      transaction_type:
        type: string
        description: The type of transaction processed
        example: "sale"
      verified_by_pin:
        type: boolean
        description: Determines if the transaction was verified by pin entry
        example: false


  DeviceInfo:
    type: object
    properties:
      name:
        type: string
        description: The name of the device
      serialno:
        type: string
        description: The serial number of the device
      portable:
        type: boolean
        description: Whether the device is portable
      busy:
        type: boolean
        description: Whether the device is busy or available for a transaction
      battery_charging:
        type: boolean
        description: Whether the device is currently charging
      battery_percentage:
        type: integer
        description: A percentage value of the battery
      printer:
        type: boolean
        description: Whether the device has a printer

  Result:
    type: object
    required:
      - message
      - success
    properties:
      message:
        type: string
        description: A message related to the request. If the action was successful the message will contain information that may be disaplyed back to the end user or if the action success is false, the message will contain an error message explaining the error. The message will not convey sensitive information.
      success:
        type: boolean
        description: A boolean result of the action requested



schemes:
 - https

host: ip-XXX-XXX-XXX-XXX.devices.kineticsmart.com
basePath: /api/v1